# Generated by Django 6.0.1 on 2026-02-06 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name_snapshot', models.CharField(max_length=255)),
                ('program_status', models.CharField(choices=[('draft', '下書き'), ('running', '実行中'), ('paused', '一時停止中'), ('finished', '完了'), ('interrupted', '中断')], default='draft', max_length=20)),
                ('started_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('paused_at', models.DateTimeField(null=True)),
                ('total_elapsed_sec', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'program_runs',
            },
        ),
    ]
