# Generated by Django 6.0.1 on 2026-02-07 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index_snapshot', models.IntegerField()),
                ('timer_name_snapshot', models.CharField(max_length=255)),
                ('duration_sec_snapshot', models.IntegerField()),
                ('sound_file_snapshot', models.CharField(max_length=255)),
                ('category_snapshot', models.CharField(max_length=255)),
                ('timer_status', models.CharField(choices=[('pending', '初期状態'), ('running', '実行中'), ('paused', '一時停止中'), ('finished', '完了'), ('skipped', 'スキップ'), ('interrupted', '中断')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(null=True)),
                ('ended_a', models.DateTimeField(null=True)),
                ('paused_at', models.DateTimeField(null=True)),
                ('elapsed_sec', models.IntegerField(null=True)),
                ('memo', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('program_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer_runs', to='runs.programrun')),
            ],
            options={
                'db_table': 'timer_runs',
            },
        ),
    ]
