# Generated by Django 6.0.1 on 2026-02-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_timerrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programrun',
            name='program_status',
            field=models.CharField(choices=[('draft', '下書き'), ('start', '実行中'), ('resume', '実行中'), ('pause', '一時停止中'), ('finish', '完了'), ('interrupt', '中断')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='timerrun',
            name='timer_status',
            field=models.CharField(choices=[('pending', '初期状態'), ('start', '初期開始'), ('resume', '再開'), ('pause', '一時停止中'), ('finish', '完了'), ('skip', 'スキップ'), ('interrupt', '中断')], default='pending', max_length=20),
        ),
    ]
