# Generated by Django 6.0.1 on 2026-02-08 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_program_table'),
        ('runs', '0003_alter_programrun_program_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programrun',
            name='program_status',
        ),
        migrations.RemoveField(
            model_name='timerrun',
            name='ended_a',
        ),
        migrations.RemoveField(
            model_name='timerrun',
            name='timer_status',
        ),
        migrations.AddField(
            model_name='programrun',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='program_runs', to='programs.program'),
        ),
        migrations.AddField(
            model_name='programrun',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('running', '実行中'), ('paused', '一時停止中'), ('finished', '完了'), ('interrupted', '中断')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='timerrun',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timerrun',
            name='status',
            field=models.CharField(choices=[('pending', '初期状態'), ('running', '実行中'), ('paused', '一時停止中'), ('finished', '完了'), ('skipped', 'スキップ'), ('interrupted', '中断')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='programrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='programrun',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programrun',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programrun',
            name='program_name_snapshot',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='programrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programrun',
            name='total_elapsed_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='programrun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='timerrun',
            name='category_snapshot',
            field=models.CharField(choices=[('focus', '集中'), ('break', '休憩'), ('refresh', 'リフレッシュ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timerrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timerrun',
            name='duration_sec_snapshot',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='timerrun',
            name='elapsed_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timerrun',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timerrun',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timerrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timerrun',
            name='timer_name_snapshot',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timerrun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
