# Generated by Django 6.0.1 on 2026-02-08 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_program_table'),
        ('runs', '0004_remove_programrun_program_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programrun',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_runs', to='programs.program'),
        ),
    ]
