# Generated by Django 6.0.1 on 2026-02-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0003_alter_timer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='is_active',
        ),
    ]
