# Generated by Django 6.0.1 on 2026-02-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='programtimer',
            table='program_timers',
        ),
    ]
