# Generated by Django 6.0.1 on 2026-02-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_programtimer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='program',
            table='programs',
        ),
    ]
